name: 编译发行

on:
  workflow_dispatch:
    inputs:
      version:
        description: 版本号
        required: true
        default: 0.0.0
jobs:
  build:
    name: 编译
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: 设置 node lts/*
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: 安装 pnpm
        uses: pnpm/action-setup@v3
        with:
          run_install: |
            - args: [--frozen-lockfile]

      - name: 引入签名密钥
        env:
          CHROME_PEM: ${{ secrets.CHROME_PEM }}
        run: |
          echo "$CHROME_PEM" > ./beriberi.pem
          chmod 600 ./beriberi.pem

      - name: 安装依赖
        run: pnpm install

      - name: Chrome 插件编译
        run: pnpm build

      - name: Chrome 打包
        run: pnpm pack:crx && pnpm pack:zip

      - name: Firefox 插件编译
        run: pnpm build-firefox

      - name: Firefox 打包
        run: pnpm pack:xpi

      # - name: 上传
      #   uses: actions/upload-artifact@v4.3.1
      #   with:
      #     name: extension
      #     path: |
      #       extension.crx
      #       extension.zip
      #       extension.xpi

      - name: 创建发行版
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ inputs.version }}
          tag_name: ${{ inputs.version }}
          draft: false
          make_latest: true
          files: |
            extension.crx
            extension.zip
            extension.xpi
