name: 编译发行

on:
  workflow_dispatch:
    inputs:
      version:
        description: 版本号
        required: true
        default: 0.0.0
jobs:
  build:
    name: 编译
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: 设置 node lts/*
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: 安装 pnpm
        uses: pnpm/action-setup@v3
        with:
          run_install: |
            - args: [--frozen-lockfile]

      - name: 引入签名密钥 & 编译
        run: |
          echo "${{ secrets.CHROME_PEM }}" > ./beriberi.pem
          chmod 600 ./beriberi.pem
          pnpm install
          pnpm build
          pnpm build-firefox
          pnpm pack:crx
          pnpm pack:zip
          pnpm pack:xpi

      - name: 创建发行版
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ inputs.version }}
          tag_name: ${{ inputs.version }}
          draft: false
          make_latest: true
          files: |
            extension.crx
            extension.zip
            extension.xpi
